.github/workflows/downstream.yml

ci: add a downstream tailwindcss-rails integration test (main)

---

lib/tailwindcss/ruby/upstream.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-alpha.30

dep: bump tailwindcss to v4.0.0-alpha.30

---

Gemfile.lock
lib/tailwindcss/ruby/upstream.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-alpha.31

dep: update tailwindcss to v4.0.0-alpha.31

---

Gemfile.lock
lib/tailwindcss/ruby/upstream.rb

- https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-alpha.32
- https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-alpha.33

dep: tailwindcss to 4.0.0-alpha.33

---

lib/tailwindcss/ruby/upstream.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-alpha.34

dep: tailwindcss v4.0.0-alpha.34

---

lib/tailwindcss/ruby/upstream.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.15

dep: tailwindcss v3.4.15

---

lib/tailwindcss/ruby/upstream.rb

See:
- https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-alpha.35
- https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-alpha.36

dep: update tailwindcss to v4.0.0-alpha.36

---

lib/tailwindcss/ruby/upstream.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-beta.3

dep: bump tailwindcss to v4.0.0-beta.3

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

and version bump this gem to v4.0.0.beta.5
https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-beta.5

dep: update tailwindcss to 4.0.0-beta.5

---

CHANGELOG.md
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-beta.6

dep: update to Tailwind CSS v4.0.0-beta.6

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-beta.8

dep: update to Tailwind CSS v4.0.0-beta.8

---

CHANGELOG.md
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.17

dep: update to Tailwind CSS v3.4.17

---

CHANGELOG.md
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0

dep: update to Tailwind CSS v4.0.0

---

CHANGELOG.md
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.1

dep: update to Tailwind CSS v4.0.1

---

CHANGELOG.md
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.2

dep: update to Tailwind CSS v4.0.2

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.3

dep: update to Tailwind CSS v4.0.3

---

CHANGELOG.md
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.4

dep: update to Tailwind CSS v4.0.4

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.5

dep: update to Tailwind CSS v4.0.5

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.7

dep: update to Tailwind CSS v4.0.7

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.8

dep: update to Tailwind CSS v4.0.8

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.9

dep: update to Tailwind CSS v4.0.9

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.12

dep: update to Tailwind CSS v4.0.12

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.14

dep: update to Tailwind CSS v4.0.14

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.15

dep: update to Tailwind CSS v4.0.15

---

.github/workflows/gem-install.yml

which is a prefactor to re-using that flow in an automated release pipeline
related to #50

ci: unify installation testing into a single matrix

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.16

dep: update to Tailwind CSS v4.0.16

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.1.3

dep: update to Tailwind CSS v4.1.3

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.1.4

dep: update to Tailwind CSS v4.1.4

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.1.5

dep: update to Tailwind CSS v4.1.5

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.1.6

dep: update to Tailwind CSS v4.1.6

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.1.7

dep: update to Tailwind CSS v4.1.7

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.1.8

dep: update to Tailwind CSS v4.1.8

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.1.10

dep: update to Tailwind CSS v4.1.10

---

CHANGELOG.md
Gemfile.lock
lib/tailwindcss/ruby/upstream.rb
lib/tailwindcss/ruby/version.rb

https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.1.11

dep: update to Tailwind CSS v4.1.11
